version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:6.1.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  python_consumer:
    build:
    context: .
    dockerfile: Dockerfile
    container_name: python_consumer
    depends_on:
      - kafka
    volumes:
      - ./consumer.py:/app/consumer.py
    command: python /app/consumer.py

  python_producer:
    build:
    context: .
    dockerfile: Dockerfile
    container_name: python_producer
    depends_on:
      - kafka
    volumes:
      - ./producer.py:/app/producer.py
    command: python /app/producer.py

